version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: gertag-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gertag
      MYSQL_USER: gertag_user
      MYSQL_PASSWORD: gertag_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
