spring.datasource.url=jdbc:mysql://localhost:3308/gertag
spring.datasource.username=gertag_user
spring.datasource.password=gertag_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
